# Generated by Django 2.0.7 on 2019-08-13 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id_choice', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('choice_text', models.CharField(max_length=200)),
                ('is_selected', models.BooleanField(default=False)),
                ('is_correct', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Pass_test_end_session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_test', models.CharField(max_length=10)),
                ('id_student', models.CharField(max_length=10)),
                ('q1', models.TextField()),
                ('q2', models.TextField()),
                ('q3', models.TextField()),
                ('q4', models.TextField()),
                ('q5', models.TextField()),
                ('q6', models.TextField()),
                ('q7', models.TextField()),
                ('q8', models.TextField()),
                ('q9', models.TextField()),
                ('q10', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pass_test_mcq_end_session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_test', models.CharField(max_length=10)),
                ('id_student', models.CharField(max_length=10)),
                ('id_q', models.IntegerField()),
                ('input_answer_num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id_question', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('question_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id_test', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Test_end_session',
            fields=[
                ('id_test', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('q1', models.TextField()),
                ('q2', models.TextField()),
                ('q3', models.TextField()),
                ('q4', models.TextField()),
                ('q5', models.TextField()),
                ('q6', models.TextField()),
                ('q7', models.TextField()),
                ('q8', models.TextField()),
                ('q9', models.TextField()),
                ('q10', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Test_mcq_end_session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_test', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=50)),
                ('id_q', models.IntegerField()),
                ('question', models.CharField(max_length=50)),
                ('answer_num', models.IntegerField()),
                ('answer_num_exp', models.IntegerField()),
                ('answer_text_correspnd', models.TextField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='test_mcq_end_session',
            unique_together={('id_test', 'id_q')},
        ),
        migrations.AddField(
            model_name='question',
            name='id_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.Test'),
        ),
        migrations.AlterUniqueTogether(
            name='pass_test_mcq_end_session',
            unique_together={('id_test', 'id_student', 'id_q')},
        ),
        migrations.AlterUniqueTogether(
            name='pass_test_end_session',
            unique_together={('id_test', 'id_student')},
        ),
        migrations.AddField(
            model_name='choice',
            name='id_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.Question'),
        ),
        migrations.AddField(
            model_name='choice',
            name='id_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.Test'),
        ),
    ]
