# Generated by Django 2.2.5 on 2020-02-11 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DynMCQInfo',
            fields=[
                ('id_test', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('print_test', models.BooleanField(default=False)),
                ('questions', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='DynMCQquestion',
            fields=[
                ('q_num', models.AutoField(primary_key=True, serialize=False)),
                ('q_text', models.TextField()),
                ('nb_ans', models.CharField(max_length=10)),
                ('right_ans', models.IntegerField(null=True)),
                ('activated', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DynTestInfo',
            fields=[
                ('id_test', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=10)),
                ('nb_q', models.CharField(max_length=10)),
                ('print_test', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MCQTest',
            fields=[
                ('id_test', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('q1', models.TextField()),
                ('r11', models.TextField()),
                ('r12', models.TextField()),
                ('r13', models.TextField()),
                ('r14', models.TextField()),
                ('r1', models.IntegerField()),
                ('q2', models.TextField()),
                ('r21', models.TextField()),
                ('r22', models.TextField()),
                ('r23', models.TextField()),
                ('r24', models.TextField()),
                ('r2', models.IntegerField()),
                ('q3', models.TextField()),
                ('r31', models.TextField()),
                ('r32', models.TextField()),
                ('r33', models.TextField()),
                ('r34', models.TextField()),
                ('r3', models.IntegerField()),
                ('q4', models.TextField()),
                ('r41', models.TextField()),
                ('r42', models.TextField()),
                ('r43', models.TextField()),
                ('r44', models.TextField()),
                ('r4', models.IntegerField()),
                ('q5', models.TextField()),
                ('r51', models.TextField()),
                ('r52', models.TextField()),
                ('r53', models.TextField()),
                ('r54', models.TextField()),
                ('r5', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id_test', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Test_end_session',
            fields=[
                ('id_test', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('q1', models.TextField()),
                ('q2', models.TextField()),
                ('q3', models.TextField()),
                ('q4', models.TextField()),
                ('q5', models.TextField()),
                ('q6', models.TextField()),
                ('q7', models.TextField()),
                ('q8', models.TextField()),
                ('q9', models.TextField()),
                ('q10', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Test_mcq_end_session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_test', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=50)),
                ('id_q', models.IntegerField()),
                ('question', models.CharField(max_length=50)),
                ('answer_num', models.IntegerField()),
                ('answer_num_exp', models.IntegerField()),
                ('answer_text_correspnd', models.TextField()),
            ],
            options={
                'unique_together': {('id_test', 'id_q')},
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id_question', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('question_text', models.CharField(max_length=200)),
                ('id_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.Test')),
            ],
        ),
        migrations.CreateModel(
            name='Pass_test_mcq_end_session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_test', models.CharField(max_length=10)),
                ('id_student', models.CharField(max_length=10)),
                ('id_q', models.IntegerField()),
                ('input_answer_num', models.IntegerField()),
            ],
            options={
                'unique_together': {('id_test', 'id_student', 'id_q')},
            },
        ),
        migrations.CreateModel(
            name='Pass_test_end_session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_test', models.CharField(max_length=10)),
                ('id_student', models.CharField(max_length=10)),
                ('q1', models.TextField()),
                ('q2', models.TextField()),
                ('q3', models.TextField()),
                ('q4', models.TextField()),
                ('q5', models.TextField()),
                ('q6', models.TextField()),
                ('q7', models.TextField()),
                ('q8', models.TextField()),
                ('q9', models.TextField()),
                ('q10', models.TextField()),
            ],
            options={
                'unique_together': {('id_test', 'id_student')},
            },
        ),
        migrations.CreateModel(
            name='Pass_MCQTest_end_session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_test', models.CharField(max_length=10)),
                ('id_student', models.CharField(max_length=10)),
                ('id_MCQTest', models.CharField(max_length=10)),
                ('q1', models.IntegerField()),
                ('q2', models.IntegerField()),
                ('q3', models.IntegerField()),
                ('q4', models.IntegerField()),
                ('q5', models.IntegerField()),
                ('mark', models.IntegerField(null=True)),
            ],
            options={
                'unique_together': {('id_test', 'id_student')},
            },
        ),
        migrations.CreateModel(
            name='Pass_DynTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_test', models.CharField(max_length=10, null=True)),
                ('id_student', models.CharField(max_length=10)),
                ('q_num', models.CharField(max_length=10, null=True)),
                ('r_text', models.TextField()),
            ],
            options={
                'unique_together': {('id_test', 'id_student', 'q_num')},
            },
        ),
        migrations.CreateModel(
            name='Pass_DynMCQTest_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_test', models.CharField(max_length=10, null=True)),
                ('id_student', models.CharField(max_length=10, null=True)),
                ('attempt', models.IntegerField(null=True)),
                ('mark', models.IntegerField(null=True)),
                ('time', models.CharField(max_length=15, null=True)),
            ],
            options={
                'unique_together': {('id_test', 'id_student', 'attempt')},
            },
        ),
        migrations.CreateModel(
            name='Pass_DynMCQTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_test', models.CharField(max_length=10, null=True)),
                ('id_student', models.CharField(max_length=10, null=True)),
                ('attempt', models.IntegerField(null=True)),
                ('q_num', models.CharField(max_length=10, null=True)),
                ('r_ans', models.TextField()),
            ],
            options={
                'unique_together': {('id_test', 'id_student', 'attempt', 'q_num')},
            },
        ),
        migrations.CreateModel(
            name='DynTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_test', models.CharField(max_length=10, null=True)),
                ('q_num', models.IntegerField(null=True)),
                ('q_text', models.TextField()),
                ('r_text', models.TextField()),
                ('activated', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('id_test', 'q_num')},
            },
        ),
        migrations.CreateModel(
            name='DynMCQanswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_num', models.IntegerField(null=True)),
                ('ans_num', models.IntegerField(null=True)),
                ('ans_text', models.TextField()),
                ('right_ans', models.IntegerField()),
            ],
            options={
                'unique_together': {('q_num', 'ans_num')},
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id_choice', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('choice_text', models.CharField(max_length=200)),
                ('is_correct', models.BooleanField(default=False)),
                ('id_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.Question')),
                ('id_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.Test')),
            ],
        ),
    ]
