# Generated by Django 2.2.5 on 2020-02-13 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynmcqquestion',
            name='difficulty',
            field=models.TextField(default=''),
        ),
    ]
