# Generated by Django 2.2.5 on 2020-02-14 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_dynmcqquestion_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynmcqinfo',
            name='activated_for',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='dynmcqinfo',
            name='time',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='dynmcqinfo',
            name='id_test',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
