# Generated by Django 2.2.5 on 2020-02-26 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_auto_20200214_1848'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dynquestion',
            fields=[
                ('q_num', models.AutoField(primary_key=True, serialize=False)),
                ('q_text', models.TextField()),
                ('r_text', models.TextField()),
                ('activated', models.IntegerField(null=True)),
                ('difficulty', models.TextField(default='')),
            ],
        ),
        migrations.AlterField(
            model_name='dyntest',
            name='activated',
            field=models.IntegerField(null=True),
        ),
    ]
