# Generated by Django 2.2.5 on 2019-10-10 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_auto_20191009_2126'),
    ]

    operations = [
        migrations.CreateModel(
            name='MCQTest',
            fields=[
                ('id_test', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('q1', models.TextField()),
                ('r11', models.TextField()),
                ('r12', models.TextField()),
                ('r13', models.TextField()),
                ('r14', models.TextField()),
                ('r1', models.IntegerField()),
                ('q2', models.TextField()),
                ('r21', models.TextField()),
                ('r22', models.TextField()),
                ('r23', models.TextField()),
                ('r24', models.TextField()),
                ('r2', models.IntegerField()),
                ('q3', models.TextField()),
                ('r31', models.TextField()),
                ('r32', models.TextField()),
                ('r33', models.TextField()),
                ('r34', models.TextField()),
                ('r3', models.IntegerField()),
                ('q4', models.TextField()),
                ('r41', models.TextField()),
                ('r42', models.TextField()),
                ('r43', models.TextField()),
                ('r44', models.TextField()),
                ('r4', models.IntegerField()),
                ('q5', models.TextField()),
                ('r51', models.TextField()),
                ('r52', models.TextField()),
                ('r53', models.TextField()),
                ('r54', models.TextField()),
                ('r5', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='test_mcq_end_session',
            name='answer_num_exp',
            field=models.IntegerField(),
        ),
    ]
