# Generated by Django 2.2.5 on 2020-03-06 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_auto_20200226_0932'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pass_DynquestionTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_test', models.CharField(max_length=10, null=True)),
                ('id_student', models.CharField(max_length=10, null=True)),
                ('attempt', models.IntegerField(null=True)),
                ('q_num', models.CharField(max_length=10, null=True)),
                ('r_ans', models.TextField()),
            ],
            options={
                'unique_together': {('id_test', 'id_student', 'attempt', 'q_num')},
            },
        ),
    ]
