# Generated by Django 2.2.5 on 2019-10-10 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_auto_20191010_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pass_MCQTest_end_session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_test', models.CharField(max_length=10)),
                ('id_student', models.CharField(max_length=10)),
                ('q1', models.IntegerField()),
                ('q2', models.IntegerField()),
                ('q3', models.IntegerField()),
                ('q4', models.IntegerField()),
                ('q5', models.IntegerField()),
            ],
            options={
                'unique_together': {('id_test', 'id_student')},
            },
        ),
    ]
