# Generated by Django 2.2.5 on 2019-10-16 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_pass_mcqtest_end_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='pass_mcqtest_end_session',
            name='id_MCQTest',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='tests.MCQTest', verbose_name='MCQTest'),
        ),
    ]
