# Generated by Django 2.2.5 on 2020-03-06 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_pass_dynquestiontest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pass_dynquestiontest',
            old_name='r_ans',
            new_name='r_answer',
        ),
    ]
