# Generated by Django 2.2.5 on 2019-10-16 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0006_pass_mcqtest_end_session_id_mcqtest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pass_mcqtest_end_session',
            name='id_MCQTest',
            field=models.CharField(max_length=10),
        ),
    ]
