# Generated by Django 2.2.5 on 2020-03-06 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0006_auto_20200306_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynmcqinfo',
            name='release_time',
            field=models.CharField(default='', max_length=15),
        ),
    ]
