# Generated by Django 2.2.5 on 2020-03-18 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0007_dynmcqinfo_release_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='id_question',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='id_test',
        ),
        migrations.DeleteModel(
            name='DynTest',
        ),
        migrations.DeleteModel(
            name='DynTestInfo',
        ),
        migrations.DeleteModel(
            name='MCQTest',
        ),
        migrations.DeleteModel(
            name='Pass_DynTest',
        ),
        migrations.DeleteModel(
            name='Pass_MCQTest_end_session',
        ),
        migrations.DeleteModel(
            name='Pass_test_end_session',
        ),
        migrations.DeleteModel(
            name='Pass_test_mcq_end_session',
        ),
        migrations.RemoveField(
            model_name='question',
            name='id_test',
        ),
        migrations.DeleteModel(
            name='Test_end_session',
        ),
        migrations.DeleteModel(
            name='Test_mcq_end_session',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
