# Generated by Django 2.2.5 on 2019-10-17 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0007_auto_20191016_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='pass_mcqtest_end_session',
            name='note',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
