# Generated by Django 2.2.5 on 2019-11-01 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0010_auto_20191017_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_test', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=50)),
                ('q_num', models.IntegerField()),
                ('q_text', models.TextField()),
                ('r_text', models.TextField()),
            ],
            options={
                'unique_together': {('id_test', 'q_num')},
            },
        ),
    ]
