# Generated by Django 2.2.5 on 2019-11-02 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0012_pass_dyntest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pass_dyntest',
            name='id',
        ),
        migrations.AddField(
            model_name='pass_dyntest',
            name='id_pk',
            field=models.CharField(default=1, max_length=10, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
