# Generated by Django 2.2.5 on 2019-11-02 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0013_auto_20191102_1025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pass_dyntest',
            name='id_pk',
        ),
        migrations.AddField(
            model_name='pass_dyntest',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
