# Generated by Django 2.2.5 on 2019-11-02 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0014_auto_20191102_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pass_dyntest',
            name='q_num',
            field=models.IntegerField(null=True),
        ),
    ]
