# Generated by Django 2.2.5 on 2019-11-02 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0017_auto_20191102_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pass_dyntest',
            name='q_num',
            field=models.CharField(max_length=10),
        ),
    ]
