# Generated by Django 2.2.5 on 2019-11-02 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0019_auto_20191102_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pass_dyntest',
            name='q_num',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pass_mcqtest_end_session',
            name='id_MCQTest',
            field=models.CharField(max_length=10),
        ),
    ]
