# Generated by Django 2.2.5 on 2019-11-08 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0021_auto_20191106_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dyntest',
            name='id_test',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='dyntest',
            name='q_num',
            field=models.IntegerField(null=True),
        ),
    ]
