# Generated by Django 2.2.5 on 2019-11-08 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0023_auto_20191108_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='pass_dyntest',
            name='activated',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
