# Generated by Django 2.2.5 on 2019-11-08 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0024_pass_dyntest_activated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pass_dyntest',
            name='activated',
            field=models.BooleanField(default=False),
        ),
    ]
