# Generated by Django 2.2.5 on 2019-11-08 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0026_auto_20191108_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dyntest',
            name='activated',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
