# Generated by Django 2.2.5 on 2019-11-08 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0027_auto_20191108_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dyntest',
            name='activated',
            field=models.BooleanField(default=False),
        ),
    ]
