# Generated by Django 2.2.5 on 2019-11-15 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0028_auto_20191108_1916'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynMCQInfo',
            fields=[
                ('id_test', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('nb_q', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='DynMCQquestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_test', models.CharField(max_length=10, null=True)),
                ('q_num', models.IntegerField(null=True)),
                ('q_text', models.TextField()),
                ('nb_ans', models.CharField(max_length=10)),
                ('right_ans', models.IntegerField(null=True)),
            ],
            options={
                'unique_together': {('id_test', 'q_num')},
            },
        ),
        migrations.CreateModel(
            name='DynMCQanswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_test', models.CharField(max_length=10, null=True)),
                ('q_num', models.IntegerField(null=True)),
                ('ans_num', models.IntegerField(null=True)),
                ('ans_text', models.TextField()),
            ],
            options={
                'unique_together': {('id_test', 'q_num', 'ans_num')},
            },
        ),
    ]
