# Generated by Django 2.2.5 on 2019-11-15 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0029_dynmcqanswer_dynmcqinfo_dynmcqquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynmcqanswer',
            name='right_ans',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
