# Generated by Django 2.2.5 on 2019-11-15 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0030_dynmcqanswer_right_ans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynmcqanswer',
            name='right_ans',
            field=models.IntegerField(),
        ),
    ]
