# Generated by Django 2.2.5 on 2019-11-16 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0033_dynmcqquestion_activated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynmcqanswer',
            name='right_ans',
            field=models.IntegerField(null=True),
        ),
    ]
