# Generated by Django 2.2.5 on 2019-11-16 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0034_auto_20191116_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynmcqanswer',
            name='right_ans',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dynmcqquestion',
            name='activated',
            field=models.IntegerField(null=True),
        ),
    ]
