# Generated by Django 2.2.5 on 2019-11-22 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0035_auto_20191116_1241'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pass_DynMCQTest_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_test', models.CharField(max_length=10, null=True)),
                ('id_student', models.CharField(max_length=10)),
                ('mark', models.IntegerField(null=True)),
            ],
            options={
                'unique_together': {('id_test', 'id_student')},
            },
        ),
    ]
