# Generated by Django 2.2.5 on 2019-11-22 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0036_pass_dynmcqtest_info'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pass_dynmcqtest_info',
            unique_together=set(),
        ),
    ]
