# Generated by Django 2.2.5 on 2020-01-30 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0037_auto_20191122_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynmcqinfo',
            name='print_test',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dyntestinfo',
            name='print_test',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pass_dynmcqtest',
            name='attempt',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pass_dynmcqtest_info',
            name='attempt',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pass_dynmcqtest_info',
            name='time',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='pass_dynmcqtest',
            name='id_student',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pass_dynmcqtest_info',
            name='id_student',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='pass_dynmcqtest',
            unique_together={('id_test', 'id_student', 'attempt', 'q_num')},
        ),
        migrations.AlterUniqueTogether(
            name='pass_dynmcqtest_info',
            unique_together={('id_test', 'id_student', 'attempt')},
        ),
    ]
