# Generated by Django 2.2.5 on 2020-01-30 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0038_auto_20200124_1103'),
        ('tests', '0038_auto_20200130_1731'),
    ]

    operations = [
    ]
